#
# Advanced Kubernetes training by Bitnami
#

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http-sv-port # Naming is mandatory when there are multiple ports
    port: 80
    targetPort: http
  type: NodePort # We want external access
