apiVersion: batch/v1
kind: Job
metadata:
  name: ping-good
spec:
  template:
    metadata:
      name: ping
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "curl dokuwiki"
      restartPolicy: Never
